### ISSUE TITLE
Crashes with nested fibers

### ISSUE THREAD

**Issue by Sarke** [amphp/ext-fiber#11]
Before you ask "why?" I was trying to break it.

```php
<?php

class Foo
{
    public function __construct(private int $num)
    {
    }
    
    public function bar()
    {
        if (--$this->num < 1)
            return 0;

        echo $this->num, "\n";
        
        $fiber = new Fiber([$this, 'bar']);
        $fiber->start();

        return $fiber->getReturn();
    }
}

$limit = 100_000;

$foo = new Foo($limit);

$fiber = new Fiber([$foo, 'bar']);
$fiber->start();

echo $fiber->getReturn(), "\n";
```

No exception thrown, no output after 71909 for me when it dies.  Returns 255 to shell.

**Comment by kelunik** [comment]
Do you have a memory limit defined?

**Comment by Sarke** [comment]
Yes, the default 128M.  If I increase it to 512M it now runs to 67232 before it fails, but this time there's an error message:

```
Fatal error: Uncaught FiberExit: Failed to create native fiber in /app/fiber/recursion.php:17
Stack trace:
#0 /app/fiber/recursion.php(17): Fiber->start()
#1 [fiber function](0): Foo->bar()
#2 {main}
  thrown in /app/fiber/recursion.php on line 17
```

**Comment by Sarke** [comment]
But yes, memory issue was my thought too, but this second error is probably because of an signed 16-bit int overflow.  I'm counting down, so 100000 - 67232 = 32768

**Comment by trowski** [comment]
I reliably get a OOM error when a fiber is unable to be created like the one below when `memory_limit` is set to `32M`.

```
Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 4096 bytes) in /Users/aaron/Developer/ext-fiber/tests/recursion.php on line 20
```

A limit of `1G` results in the script completing for me.

Do you have `display_errors` off?

---

The exception you posted is thrown if the fiber stack cannot be allocated with `mmap`. Interesting that it failed for you after exactly 32768 fibers. What system are you running this on? There may be limits on `mmap` allocations per process.

**Comment by Sarke** [comment]
Very interesting, I've never seen a fatal error not be reported when using cli.

Yes, `display_errors` is on.  If I set `error_reporting(E_ALL);` then it does display.  But I don't have to do this when a regular (i.e. non-fiber) script runs out of memory, it should always display in the cli.

I'm running it on the command line on Linux 64-bit using the docker images I made: https://hub.docker.com/r/sarkedev/php-fiber

```
docker run --rm -v `pwd`:`pwd` -w `pwd` sarkedev/php-fiber php recursion.php
```

If I set the memory limit to `1G` I get the `Failed to create native fiber` like before.  What is your environment?

**Comment by Sarke** [comment]
Alright, so something really odd is happening here.

```php
<?php

if ($argv[1])
    error_reporting(E_ALL);

$e = error_reporting();
var_dump($e);
var_dump($e === E_ALL);

ini_set('memory_limit','8M');

function foo()
{
    $fiber = new Fiber('foo');
    $fiber->start();
}

foo();
```

```
$ php recursion.php 0
int(32767)
bool(true)
```

```
$ php recursion.php 1
int(32767)
bool(true)

Fatal error: Allowed memory size of 8388608 bytes exhausted (tried to allocate 4096 bytes) in /app/fiber/recursion.php on line 15
```

**Comment by trowski** [comment]
`INI_INT` was returning 0 if the setting wasn't explicitly set, so error reporting in fibers was disabled in that case. Tests didn't catch this since `error_reporting` is explicitly set to `E_ALL`. That OOM error should always display now, unless of course you actually turn off error reporting. 😊

Regarding the `Failed to create native fiber` exception, what do you get when you run `sysctl vm.max_map_count` on the docker image on your system. I get `262144`. After raising the recursion count it fails after 131,072 fibers, so apparently you can expect half that number.

I'm normally running things on macOS. I can't seem to hit a limit with `mmap`, even with a million fibers and setting the memory limit to `16G`.

**Comment by Sarke** [comment]
Great!  Should I open a new issue for the `Failed to create native fiber` issue, or that is an acceptable error?

**Comment by trowski** [comment]
No, that's an acceptable error if `mmap` is unable to allocate memory. Real-world applications should not hit that limit.

**Comment by Sarke** [comment]
The reply above was before I saw your reply.

I get `vm.max_map_count = 65530`.

Ok, so maybe the 32768 was just a coincidence.

```php
<?php

register_shutdown_function(function() {
	global $num;
	echo $num, "\n";
});

ini_set('memory_limit','16G');

function foo()
{
	global $num;
	$num++;
	$fiber = new Fiber('foo');
	$fiber->start();
}

$num = 0;
foo();
```

```
Fatal error: Uncaught FiberExit: Failed to create native fiber in /app/mmap.php:15
Stack trace:
#0 /app/mmap.php(15): Fiber->start()
#1 [fiber function](0): foo()
#2 {main}
  thrown in /app/mmap.php on line 15
32769
```

```
Fatal error: Uncaught FiberExit: Failed to create native fiber in /app/mmap.php:15
Stack trace:
#0 /app/mmap.php(15): Fiber->start()
#1 [fiber function](0): foo()
#2 {main}
  thrown in /app/mmap.php on line 15
32708
```

Is this a global limit?  If so, I have A LOT open and running in the background.

**Comment by Sarke** [comment]
Progress!  Different errors:

```
$ sudo sysctl -w vm.max_map_count=262144
vm.max_map_count = 262144

$ php mmap.php

munmap() failed: [12] Out of memory

munmap() failed: [12] Out of memory

Fatal error: Uncaught FiberExit: Failed to create native fiber in /app/mmap.php:15
Stack trace:
#0 /app/mmap.php(15): Fiber->start()
#1 [fiber function](0): foo()
#2 {main}
  thrown in /app/mmap.php on line 15
131073
```

**Comment by trowski** [comment]
I also saw `munmap() failed: [12] Out of memory` just before it failed on docker. Clearly it's hitting an OS limit and failing, so all seems to be working as expected.

**Comment by Sarke** [comment]
Well if I can't have 130,000 fibers then this extension is stupid.

/s

Seriously though, I'm really excited about this extension.

**Comment by trowski** [comment]
> Well if I can't have 130,000 fibers then this extension is stupid.

But you can sir! Simply raise that limit, step back, and wait watch your memory be completely consumed by fiber stacks!

Raising the recursion depth to one million consumed over 12GB of memory before the script finished, then hung for a several seconds while the garbage collector did its work.

> Seriously though, I'm really excited about this extension.

Me too! 🤓
