### ISSUE TITLE
Unresolved fibers

### ISSUE THREAD

**Issue by Sarke** [amphp/ext-fiber#16]
Hi, me again.

Currently, if the main thread finishes and there are suspended fibers left, it just finishes silently.  Since PHP has been getting more strict lately, I am think there should be at least an `E_WARNING` raised, as this is most likely unintended.  It would also make debugging easier.

To go along with this, should there be a "nice" way to end suspended fibers?  Maybe something as simple as `$fiber->kill()`?

**Comment by trowski** [comment]
Fibers are destroyed in the same way as unfinished Generators – if the last yield (suspend) point was within a try block with a finally block, the finally block is executed, the VM and C stack are freed, and the object is destroyed.

It is not necessarily an error to have an unfinished fiber, so I wouldn't want to force that upon users. A fiber object could be decorated in user code to issue a warning in __destruct if the fiber was not finished.

**Comment by Sarke** [comment]
Makes sense.
