### ISSUE TITLE
Compiling on mac M1

### ISSUE THREAD

**Issue by brendt** [amphp/ext-fiber#17]
Trying to compile on Mac M1 Big Sur, I'm getting this error when running `make`:

```php
/Users/brent/Dev/ext-fiber/boost/asm/make_arm_aapcs_macho_gas.S:45:5: error: unexpected token at start of statement
    @ shift address in A1 to lower 16 byte boundary
    ^
/Users/brent/Dev/ext-fiber/boost/asm/make_arm_aapcs_macho_gas.S:46:9: error: invalid operand for instruction
    bic a1, a1, #15
        ^
```

There are in total around 25 of these errors, but I figure they all have the same cause. Any pointers?

**Comment by trowski** [comment]
I may have messed this up in [here](https://github.com/amphp/ext-fiber/blob/721b8d9fc090274e3f00bd1c18d9280eef1824d9/src/fiber_asm.c#L98). I thought I was aligning to 16-byte boundaries with `& ~0xf`.

Do you have a few minutes to jump in IRC chat or room 11? Seems my Intel Mac is more forgiving on stack alignment.

**Comment by brendt** [comment]
@trowski is tomorrow ok? Shoot me an email: brent@spatie.be, I'm happy to help!

**Comment by trowski** [comment]
Yep, tomorrow works for me.

**Comment by trowski** [comment]
Looked at this again and I think the config used the wrong assembly file. Can you change [this line](https://github.com/amphp/ext-fiber/blob/721b8d9fc090274e3f00bd1c18d9280eef1824d9/config.m4#L25) in config.m4 to `[arm64*|aarch64*], [fiber_cpu="arm64"],` then run `phpize --clean`, then rebuild the extension.

**Comment by brendt** [comment]
Changling that line didn't solve the problem, I'll be in room 11 :)
