### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by dbalabka** [amphp/ext-fiber#6]
It would be great to have a docker image for experimenting with the extension.

**Comment by dbalabka** [comment]
I've created Dockerfile:
https://github.com/dbalabka/doctrine-mysql-fiber-driver/blob/master/Dockerfile

**Comment by Sarke** [comment]
I made an autobuild here:

https://hub.docker.com/r/sarkedev/php-fiber

It's got the latest version of both the extension and php images.

**Comment by trowski** [comment]
Closed with #13.
