### ISSUE TITLE
Issue with amp:v3 + docker php-apache

### ISSUE THREAD

**Issue by glickel** [amphp/ext-fiber#7]
Hello,
I have an issue with the stack docker php-apache + fiber extension + amp:v3. Some times the HTTP requests work fine, some times not and I have this issue:
```
Uncaught FiberError: Cannot call Fiber::this() within a fiber scheduler in /var/www/html/vendor/amphp/amp/lib/functions.php:28
```

Here is an example [https://github.com/glickel/issue-php-apache-fiber-amp](https://github.com/glickel/issue-php-apache-fiber-amp) witth docker-compose.

Since it happens some times only, I think the issue come frome the extension himself.

**Comment by kelunik** [comment]
Do you have a full stack trace for the error?

**Comment by trowski** [comment]
I can reproduce this with the docker container provided. The stack trace is simply:

```
#0 /var/www/html/vendor/amphp/amp/lib/functions.php(28): Fiber::this()
#1 /var/www/html/public/index.php(8): Amp\await(Object(Amp\Internal\PrivatePromise))
#2 {main}
```

That makes no sense. `zend_fiber_is_scheduler` should not be returning true for the main fiber.

**Comment by trowski** [comment]
@glickel Please give it a try again. The current fiber pointer was left over from prior requests, resulting in `{main}` appearing to be a scheduler fiber. I've only tested the extension with cli, so testing on apache/nginx would be helpful.

**Comment by glickel** [comment]
@trowski it works well now with my use case, thank you 👍
