### ISSUE TITLE
Can I use this with PHP-FPM？

### ISSUE THREAD

**Issue by nauxliu** [amphp/ext-fiber#8]

**Comment by kelunik** [comment]
This is intended, yes. Please report any issues that arise!

**Comment by nauxliu** [comment]
Great! Thanks for the info, what is the minimum required php version? Can I use this with 7.4?

**Comment by enumag** [comment]
No. IIRC it is only compatible with 8.0.

**Comment by kelunik** [comment]
Currently not, because we rely on a new API that's been introduced in PHP 8.0, so currently PHP 8.0 is the minimum version. We'd be happy if anyone knows of a similar mechanism we could use on PHP 7.x.

**Comment by Freeaqingme** [comment]
> No. IIRC it is only compatible with 8.0.

Perhaps it's an idea to document this in the readme?

**Comment by kelunik** [comment]
Please create a PR if you want to see it there.
